### ISSUE TITLE
Error message running ModelDataTable demo code

### ISSUE THREAD

**Issue by jfabiani** [iron3oxide/fletched#14]
Exception has occurred: ImportError
cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)
  File "/home/johnf/flet_projects/fletched-main/polars_fletched/test1.py", line 3, in <module>
    from fletched.controls import DataTableConfig, ModelDataTable, ModelDataTableConfig
ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)

**Comment by iron3oxide** [comment]
Should be fixed in 0.5.1 which I just released

**Comment by jfabiani** [comment]
After upgrading fletched "pip install fletched --upgrade" I can confirm 
that fix worked for me.

Still waiting for a good demo on the use of fletched.  Hope to see it soon.

Johnf
